PROJECT_NAME="ChatBI"

BACKEND_CORS_ORIGINS=${CHATBI_CORS_ORIGINS}
SECRET_KEY=${CHATBI_SECRET_KEY}

DEFAULT_PWD=${CHATBI_DEFAULT_PWD}

LOG_LEVEL=${CHATBI_LOG_LEVEL}
SQL_DEBUG=False

CACHE_TYPE=${CHATBI_CACHE_TYPE}

POSTGRES_SERVER=${CHATBI_DB_HOST}
POSTGRES_PORT=${CHATBI_DB_PORT}
POSTGRES_DB=${CHATBI_DB_DB}
POSTGRES_USER=${CHATBI_DB_USER}
POSTGRES_PASSWORD=${CHATBI_DB_PASSWORD}

SERVER_IMAGE_HOST=${CHATBI_SERVER_IMAGE_HOST}
