"""052_add_permission_oid

Revision ID: a1b2c3d4e5f6
Revises: cb12c4238120
Create Date: 2026-01-06 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a1b2c3d4e5f6'
down_revision = 'cb12c4238120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 ds_permission 表的 oid 字段
    op.add_column('ds_permission', sa.Column('oid', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ds_permission', 'oid')
    # ### end Alembic commands ###
