"""053_add_data_training_specific_ds

Revision ID: b2c3d4e5f6g7
Revises: a1b2c3d4e5f6
Create Date: 2026-01-15 10:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b2c3d4e5f6g7'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 specific_ds 字段到 data_training 表
    # specific_ds=False 表示全局知识库（适用于所有数据源）
    # specific_ds=True 表示仅适用于特定数据源
    op.add_column('data_training', sa.Column('specific_ds', sa.Boolean(), nullable=True, server_default='false'))
    
    # 将现有数据的 specific_ds 设置为 True（因为它们都有 datasource 关联）
    op.execute("UPDATE data_training SET specific_ds = true WHERE datasource IS NOT NULL OR advanced_application IS NOT NULL")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_training', 'specific_ds')
    # ### end Alembic commands ###
