"""054_add_data_training_datasource_ids

Revision ID: c3d4e5f6g7h8
Revises: b2c3d4e5f6g7
Create Date: 2026-01-15 19:45:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c3d4e5f6g7h8'
down_revision = 'b2c3d4e5f6g7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 添加 datasource_ids 字段到 data_training 表（JSONB 类型，存储多个数据源 ID）
    op.add_column('data_training', sa.Column('datasource_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=True, server_default='[]'))
    
    # 将现有数据的 datasource 转换为 datasource_ids 数组
    op.execute("""
        UPDATE data_training 
        SET datasource_ids = jsonb_build_array(datasource) 
        WHERE datasource IS NOT NULL AND (datasource_ids IS NULL OR datasource_ids = '[]'::jsonb)
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('data_training', 'datasource_ids')
    # ### end Alembic commands ###
