"""055_fix_data_training_specific_ds

Revision ID: d4e5f6g7h8i9
Revises: c3d4e5f6g7h8
Create Date: 2026-01-15 19:50:00.000000

修复：将现有 SQL 示例数据改为"所有数据源"（全局知识库）
原因：SQL 示例通常是通用的查询模式，应该默认适用于所有数据源
"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = 'd4e5f6g7h8i9'
down_revision = 'c3d4e5f6g7h8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 将所有 SQL 示例数据改为"所有数据源"（全局知识库）
    # specific_ds=false 表示适用于所有数据源
    op.execute("UPDATE data_training SET specific_ds = false")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 恢复：将有 datasource 的数据改回特定数据源
    op.execute("UPDATE data_training SET specific_ds = true WHERE datasource IS NOT NULL OR advanced_application IS NOT NULL")
    # ### end Alembic commands ###
