# 基础配置
## 安装目录
CHATBI_BASE=/opt
## ChatBI 端口
CHATBI_WEB_PORT=8000
CHATBI_MCP_PORT=8001

# 数据库配置
## 是否使用外部数据库
CHATBI_EXTERNAL_DB=false
## 数据库地址
CHATBI_DB_HOST=localhost
## 数据库端口 (仅使用外部数据库时才生效)
CHATBI_DB_PORT=5432
## ChatBI 数据库库名
CHATBI_DB_DB=chatbi
## 数据库用户名
CHATBI_DB_USER=root
## 数据库密码，密码如包含特殊字符，请用双引号引起来，例如 CHATBI_DB_PASSWORD="Test@4&^%*^"
CHATBI_DB_PASSWORD=Password123@pg

# 其他配置
## 普通用户默认密码
CHATBI_DEFAULT_PWD=ChatBI@123456
## ChatBI Secret Key
CHATBI_SECRET_KEY=y5txe1mRmS_JpOrUzFzHEu-kIQn3lf7ll0AOv9DQh0s
## Cross-Origin Resource Sharing (CORS) 设置
CHATBI_CORS_ORIGINS=http://localhost,http://localhost:5173,https://localhost,https://localhost:5173
## 日志级别 DEBUG, INFO, WARNING, ERROR
CHATBI_LOG_LEVEL="INFO"
## 缓存类型
CHATBI_CACHE_TYPE="memory"
## MCP 图片存储路径
CHATBI_SERVER_IMAGE_HOST=http://YOUR_SERVER_IP:MCP_PORT/images/
